-- First pass: the constraints a sane schema would have, applied straight onto
-- the legacy data.

ALTER TABLE CUSTOMERS MODIFY (FULL_NAME NOT NULL, PAN NOT NULL);
ALTER TABLE CUSTOMERS ADD CONSTRAINT UQ_CUSTOMERS_PAN UNIQUE (PAN);
ALTER TABLE CUSTOMERS ADD CONSTRAINT CK_CUSTOMERS_PAN_FORMAT CHECK (REGEXP_LIKE(PAN, '^[A-Z]{5}[0-9]{4}[A-Z]$'));

ALTER TABLE POLICIES MODIFY (POLICY_NO NOT NULL, CUSTOMER_ID NOT NULL, PREMIUM_MODE NOT NULL, PREMIUM_AMOUNT NOT NULL, NEXT_DUE_DATE NOT NULL);
CREATE UNIQUE INDEX UX_POLICIES_POLICY_NO ON POLICIES (UPPER(POLICY_NO));
ALTER TABLE POLICIES ADD CONSTRAINT FK_POLICIES_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (CUSTOMER_ID);
ALTER TABLE POLICIES ADD CONSTRAINT CK_POLICIES_MODE CHECK (PREMIUM_MODE IN ('YEARLY', 'HALF_YEARLY', 'QUARTERLY', 'MONTHLY'));
ALTER TABLE POLICIES MODIFY (PREMIUM_AMOUNT NUMBER(12,2));

ALTER TABLE PAYMENTS MODIFY (POLICY_ID NOT NULL, AMOUNT NOT NULL, PAID_AT NOT NULL, IDEMPOTENCY_KEY NOT NULL);
ALTER TABLE PAYMENTS ADD CONSTRAINT FK_PAYMENTS_POLICY FOREIGN KEY (POLICY_ID) REFERENCES POLICIES (POLICY_ID);
ALTER TABLE PAYMENTS ADD CONSTRAINT UQ_PAYMENTS_IDEM_KEY UNIQUE (IDEMPOTENCY_KEY);
