--------------------------------------------------------------------------------
-- V005  Constraints and indexes, now that the data can satisfy them
--
-- Every index here is listed in NOTES.md with the query it serves.
--------------------------------------------------------------------------------

-- CUSTOMERS -------------------------------------------------------------------
ALTER TABLE CUSTOMERS MODIFY (FULL_NAME NOT NULL, PAN NOT NULL, MOBILE NOT NULL, CREATED_AT NOT NULL);

ALTER TABLE CUSTOMERS ADD (
  CONSTRAINT CK_CUSTOMERS_PAN_FORMAT   CHECK (REGEXP_LIKE(PAN, '^[A-Z]{5}[0-9]{4}[A-Z]$')),
  CONSTRAINT CK_CUSTOMERS_MOBILE       CHECK (REGEXP_LIKE(MOBILE, '^[6-9][0-9]{9}$')),
  CONSTRAINT CK_CUSTOMERS_EMAIL        CHECK (EMAIL IS NULL OR REGEXP_LIKE(EMAIL, '^[^@[:space:]]+@[^@[:space:]]+\.[a-z]{2,}$')),
  CONSTRAINT CK_CUSTOMERS_NAME_TRIMMED CHECK (FULL_NAME = TRIM(FULL_NAME)),
  CONSTRAINT FK_CUSTOMERS_PAN_CONFLICT FOREIGN KEY (PAN_CONFLICT_OF) REFERENCES CUSTOMERS (CUSTOMER_ID)
);

-- One PAN, one customer. The three legacy rows sharing a PAN are told apart
-- by PAN_CONFLICT_OF (NULL for the first, the first's id for the others), so
-- they fit; any new row reusing a PAN has PAN_CONFLICT_OF NULL and collides.
CREATE UNIQUE INDEX UX_CUSTOMERS_PAN ON CUSTOMERS (PAN, NVL2(PAN_CONFLICT_OF, CUSTOMER_ID, NULL));

-- POLICIES --------------------------------------------------------------------
ALTER TABLE POLICIES MODIFY (
  POLICY_NO NOT NULL, CUSTOMER_ID NOT NULL, PLAN_NAME NOT NULL, SUM_ASSURED NOT NULL,
  COMMENCEMENT_DATE NOT NULL, DUE_DAY NOT NULL, CREATED_AT NOT NULL
);

ALTER TABLE POLICIES ADD (
  CONSTRAINT FK_POLICIES_MODE            FOREIGN KEY (PREMIUM_MODE) REFERENCES PREMIUM_MODES (MODE_CODE),
  CONSTRAINT FK_POLICIES_NO_CONFLICT     FOREIGN KEY (POLICY_NO_CONFLICT_OF) REFERENCES POLICIES (POLICY_ID),
  CONSTRAINT CK_POLICIES_POLICY_NO       CHECK (POLICY_NO = UPPER(TRIM(POLICY_NO))),
  CONSTRAINT CK_POLICIES_PREMIUM         CHECK (PREMIUM_AMOUNT > 0),
  CONSTRAINT CK_POLICIES_SUM_ASSURED     CHECK (SUM_ASSURED > 0),
  CONSTRAINT CK_POLICIES_DUE_DAY         CHECK (DUE_DAY BETWEEN 1 AND 31),
  CONSTRAINT CK_POLICIES_DATES_ARE_DATES CHECK (NEXT_DUE_DATE = TRUNC(NEXT_DUE_DATE)
                                                AND FIRST_UNPAID_DUE_DATE = TRUNC(FIRST_UNPAID_DUE_DATE)
                                                AND COMMENCEMENT_DATE = TRUNC(COMMENCEMENT_DATE)),
  CONSTRAINT CK_POLICIES_DUE_AFTER_START CHECK (NEXT_DUE_DATE >= COMMENCEMENT_DATE),
  -- Servicing needs a mode, a premium and a due date. A policy may lack them
  -- only while it carries a DATA_ISSUE explaining why.
  CONSTRAINT CK_POLICIES_SERVICEABLE     CHECK (DATA_ISSUE IS NOT NULL
                                                OR (PREMIUM_MODE IS NOT NULL AND PREMIUM_AMOUNT IS NOT NULL
                                                    AND NEXT_DUE_DATE IS NOT NULL))
);

-- Policy 5021 points at customer 999999, which does not exist. We will not
-- invent a customer, and the policy is real business. NOVALIDATE enforces the
-- key for every new or changed row while tolerating that one legacy orphan.
ALTER TABLE POLICIES ADD CONSTRAINT FK_POLICIES_CUSTOMER
  FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (CUSTOMER_ID) ENABLE NOVALIDATE;

-- Same idea as UX_CUSTOMERS_PAN. POLICY_NO is stored upper-cased (checked
-- above), so a plain column index is case-insensitive in effect.
CREATE UNIQUE INDEX UX_POLICIES_POLICY_NO ON POLICIES (POLICY_NO, NVL2(POLICY_NO_CONFLICT_OF, POLICY_ID, NULL));

CREATE INDEX IX_POLICIES_CUSTOMER ON POLICIES (CUSTOMER_ID);

-- PAYMENTS --------------------------------------------------------------------
ALTER TABLE PAYMENTS MODIFY (
  POLICY_ID NOT NULL, AMOUNT NOT NULL, PAID_AT NOT NULL, IDEMPOTENCY_KEY NOT NULL,
  COVERS_DUE_DATE NOT NULL, CHANNEL NOT NULL, CREATED_AT NOT NULL
);

ALTER TABLE PAYMENTS ADD (
  CONSTRAINT FK_PAYMENTS_POLICY   FOREIGN KEY (POLICY_ID) REFERENCES POLICIES (POLICY_ID),
  CONSTRAINT FK_PAYMENTS_REQUEST  FOREIGN KEY (IDEMPOTENCY_KEY) REFERENCES PAYMENT_REQUESTS (IDEMPOTENCY_KEY),
  CONSTRAINT CK_PAYMENTS_AMOUNT   CHECK (AMOUNT > 0),
  CONSTRAINT CK_PAYMENTS_CHANNEL  CHECK (CHANNEL IN ('BRANCH', 'ONLINE', 'AGENT', 'AUTO-DEBIT')),
  CONSTRAINT CK_PAYMENTS_COVERS   CHECK (COVERS_DUE_DATE = TRUNC(COVERS_DUE_DATE)),
  -- An instalment is paid once. This is the last line of defence against a
  -- double charge, whatever the application does.
  CONSTRAINT UQ_PAYMENTS_INSTALMENT UNIQUE (POLICY_ID, COVERS_DUE_DATE)
);

CREATE INDEX IX_PAYMENTS_IDEM_KEY ON PAYMENTS (IDEMPOTENCY_KEY);

-- PAYMENT_REQUESTS ------------------------------------------------------------
ALTER TABLE PAYMENT_REQUESTS ADD (
  CONSTRAINT FK_PAYMENT_REQUESTS_POLICY FOREIGN KEY (POLICY_ID) REFERENCES POLICIES (POLICY_ID),
  CONSTRAINT CK_PAYMENT_REQUESTS_AMOUNT CHECK (AMOUNT > 0)
);
